rails-titanic-teams/config/routes.rb
Rails.application.routes.draw do

  

  root 'sessions#index'
  get '/login', to: "sessions#login", as: 'login'
  get '/signup', to: "sessions#signup", as: 'signup'
  post '/login', to: "sessions#attempt_login"
  post '/signup', to: "sessions#create"
  get '/home', to: "sessions#index", as: 'home'
  delete '/logout', to: "sessions#logout", as: "logout"

  get '/teams', to: "teams#all", as: "all_teams"

  resources :resets, only: [:new, :edit, :create, :update]

  resources :users do
    resources :teams, shallow: true
  end

  resources :superheros

end

rails-titanic-teams/app/models/superhero.rb
class Superhero < ActiveRecord::Base
  validates :name, :height, :bio, :image_url, presence: true
	has_many :affiliations, dependent: :destroy
	has_many :teams, through: :affiliations
end

rails-titanic-teams/app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  before_action :confirm_logged_in
	# before_action :confirm_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :confirm_admin, except: [:index, :show]
	before_action :set_superhero, only: [:show, :edit, :update, :destroy]
	before_action :set_team, only: [:show]

  def index
    @superheros = Superhero.all
  end

  def new
    @superhero = Superhero.new
  end

  def create
    @superhero = Superhero.create superhero_params
    if @superhero.save
      redirect_to superheros_path, flash: {success: "#{@superhero.name} added!"}
    else
      render :new
    end
  end

  def edit
  end

  def show
    @teams = Team.all
  end

  def update
    @superhero.update superhero_params
    if @superhero.save
      redirect_to superhero_path(@superhero), flash: {success: "You updated #{@superhero.name}"}
    else
      render :edit
    end
 end

  def destroy
    @superhero.destroy
    redirect_to superheros_path, alert: "#{@superhero.name} deleted"
 end

  def superhero_params
    params.require(:superhero).permit(
      :name,
      :height,
      :bio,
      :image_url,
      :team_ids => []
    )
  end

  def set_team
    @team = Team.find_by_id params[:id]
  end

  def set_superhero
    @superhero = Superhero.find_by_id params[:id]
  end
end

rails-titanic-teams/app/helpers/superheros_helper.rb
module SuperherosHelper
end

rails-titanic-teams/app/views/superheros/_form.html.erb
<%= form_for( @superhero, html:{class:"form-horizontal", role:"form"}) do |f| %>
	<%= render partial:"shared/errors", locals:{instance:@superhero} %>
	<div class="form-group">
		<%= f.label :name, class:"col-md-2"  %>
		<div class="col-sm-10">
			<%= f.text_field :name, class:"form-control", autofocus: true %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :height, class:"col-md-2"  %>
		<div class="col-sm-10">
			<%= f.number_field :height, step:"0.01", class:"form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :bio, class:"col-md-2"  %>
		<div class="col-sm-10">
			<%= f.text_area :bio, class:"form-control" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :image_url, class:"col-md-2"  %>
		<div class="col-sm-10">
			<%= f.text_field :image_url, class:"form-control" %>
		</div>
	</div>

    <div class="form-group">
    	<%= f.label :teams, class:"col-md-2"  %>
    	<div class="col-sm-7">
	    	<%= f.collection_check_boxes(:team_ids, Team.all, :id, :name) do |b| %>
	        	<span class="team-selection">
	            	<%= b.check_box %>
	            	<%= b.label %>
	        	</span>
	    	<% end %>
    	</div>
  	</div>

	<div class="actions col-sm-offset-2">
		<%= f.submit class:"btn btn-primary" %>
		<%= link_to 'Cancel', superheros_path, class:"btn btn-default" %>
	</div>

<% end %>

rails-titanic-teams/app/views/superheros/edit.html.erb
<h1 class="page-header">Edit <%= @superhero.name %></h1>
<%= render "form" %>

rails-titanic-teams/app/views/superheros/index.html.erb
<%= link_to "Add Superheroes", new_superhero_path, class:"btn btn-primary"%>

<h1 class="page-header">Superheroes!</h1>
<div class="container-fluid">
  <div class="row">
  <% @superheros.each do |superhero| %>
    <div class="col-sm-3">
      <div class="thumbnail">
        <%= image_tag(superhero.image_url) %>
        <div class="caption">
          <h3><%= superhero.name %></h3>
          <p><%= link_to "Show", superhero_path(superhero), class:"btn btn-primary" %></p>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

rails-titanic-teams/app/views/superheros/new.html.erb
<h1 class="page-header">Add a new Superhero</h1>
<%= render 'form' %>

rails-titanic-teams/app/views/superheros/show.html.erb
<h1 class="page-header"><i class="fa fa-bolt"></i> <%= @superhero.name %></h1>

<div class="team-profile row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag(@superhero.image_url, class:"img-rounded profile-img img-responsive") %>
      <div class="caption">
        <% if @superhero.team_ids.length == 0 %>
          <h3>Affiliations: <%= @superhero.team_ids.length %></h3>
          <p><%= link_to "Add Superheros to your team!", edit_superhero_path %></p>
        <% else %>
          <h3>Affiliations: <%= @superhero.team_ids.length %></h3>
          <% @superhero.team_ids.each do |team| %>
            <p class="text-primary"><%= @teams.find(team).name %></p>
          <% end %>
        <% end %>
        <p>Bio: <%= @superhero.bio %></p>
        <p>Height: <%= @superhero.height %></p>
        <% if current_user.is_admin %>
          <%= link_to "Edit", edit_superhero_path(@superhero), class:"btn btn-info" %>
          <%= link_to "Delete", @superhero, method: :delete, data: {alert: "Are you sure?"},  class:"btn btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</div>