rails-titanic-teams/config/routes.rb
Rails.application.routes.draw do

  

  root 'sessions#index'
  get '/login', to: "sessions#login", as: 'login'
  get '/signup', to: "sessions#signup", as: 'signup'
  post '/login', to: "sessions#attempt_login"
  post '/signup', to: "sessions#create"
  get '/home', to: "sessions#index", as: 'home'
  delete '/logout', to: "sessions#logout", as: "logout"

  get '/teams', to: "teams#all", as: "all_teams"

  resources :resets, only: [:new, :edit, :create, :update]

  resources :users do
    resources :teams, shallow: true
  end

  resources :superheros

end

rails-titanic-teams/app/models/user.rb
class User < ActiveRecord::Base
  has_many :teams, dependent: :destroy

  has_secure_password
  validates :username, uniqueness: {case_sensitive: false}, presence: true
  validates :avatar_url, presence: true

  def generate_password_reset_token!
     update(password_reset_token: SecureRandom.urlsafe_base64(48))
  end
end

rails-titanic-teams/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:show,:edit, :update, :destroy]
  # before_action only: [:index, :show] do
  #   prevent_tampering(params[:id].to_i, session[:user_id])
  # end

  def index
    @users = User.all
    
  end

  def show
  end

  def edit
  end

  def update
    @user.update user_params
    if @user.save
      redirect_to user_path, flash: {success: "#{@user.username} updated!"}
    else
      render :edit
    end
  end

  def destroy
    @user.destroy && session[:user_id] = nil
    redirect_to root_path, flash: {success: "#{@user.username} deleted"}
  end

  private

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(
      :username,
      :password,
      :avatar_url
    )
  end

  def ensure_correct_user
    # compare some params vs something in the session/current_user
    unless params[:id].to_i == session[:user_id]
      redirect_to all_teams_path, alert: "Not Authorized"
    end
  end
end

rails-titanic-teams/app/helpers/users_helper.rb
module UsersHelper
end

rails-titanic-teams/app/views/users/edit.html.erb
<h1 class="page-header">Edit <%= current_user.username %></h1>

<%= form_for @user, html:{class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :username, class:"control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.text_field :username, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :avatar_url, class:"control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= f.text_field :avatar_url, class:"form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <%= f.submit class:"btn btn-success text-center" %>
    </div>
  </div>
<% end %>

rails-titanic-teams/app/views/users/show.html.erb
<ul class="list-unstyled">
  <li><%= image_tag("#{current_user.avatar_url}", id:"profile-img", class:"img-rounded img-responsive") %></li>
  <li><h1><%= current_user.username %></h1></li>
</ul>

<%= link_to "Edit", edit_user_path(current_user), class:"btn btn-info" %>
<%= link_to "Delete", current_user, method: :delete, data: {alert: "Are you sure?"},  class:"btn btn-danger" %>
<%= link_to "View All Teams", user_teams_path(@user), class:"btn btn-success" %>