rails-titanic-teams/config/routes.rb
Rails.application.routes.draw do

  

  root 'sessions#index'
  get '/login', to: "sessions#login", as: 'login'
  get '/signup', to: "sessions#signup", as: 'signup'
  post '/login', to: "sessions#attempt_login"
  post '/signup', to: "sessions#create"
  get '/home', to: "sessions#index", as: 'home'
  delete '/logout', to: "sessions#logout", as: "logout"

  get '/teams', to: "teams#all", as: "all_teams"

  resources :resets, only: [:new, :edit, :create, :update]

  resources :users do
    resources :teams, shallow: true
  end

  resources :superheros

end

rails-titanic-teams/app/controllers/resets_controller.rb
class ResetsController < ApplicationController
	def new
  end

	def create
	    user = User.find_by(email: params[:email])
	    if user
	      user.generate_password_reset_token!
	      Reset.password_reset(user).deliver_now
	      redirect_to login_path, notice: "Email sent"
	    else
	      flash.now[:alert] = "Email not found"
	      render :new
	    end
	  end

  def edit
    @user = User.find_by(password_reset_token: params[:id])
    if @user
      # feels like we are missing something here
      # but, have no fear, we are just going to render edit.html.erb
    else
      redirect_to login_path, alert: "Invalid reset token"
    end
  end

  def update
    @user = User.find_by(password_reset_token: params[:id])
    if params[:user][:password].present?
      if @user && @user.update(user_params)
        @user.update(password_reset_token: nil)
        session[:user_id] = @user.id
        redirect_to root_path, flash: {success: "Password updated."}
      else
        flash.now[:notice] = "Password reset token not found."
        render :edit
      end
    else
      flash.now[:alert] = "Please enter a password"
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:password)
  end
end

rails-titanic-teams/app/helpers/resets_helper.rb
module ResetsHelper
end

rails-titanic-teams/app/views/resets/edit.html.erb
<h1>Change Your Password</h1>
<%= form_for :user, url:reset_path(@user.password_reset_token), method: :patch do |f|%>
<%= f.label :password %>
<%= f.password_field :password, autofocus: true%>

<%= f.submit "Reset Password"%>

<% end %>

rails-titanic-teams/app/views/resets/new.html.erb
<h1>Reset password</h1>

<%= form_tag resets_path do%>
<%= label_tag :email, "Email"%>
<%= text_field_tag :email%>

<%= submit_tag "Reset Password" %>

<% end %>